# Generated by Django 3.1.2 on 2021-01-08 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, null=True)),
                ('title', models.CharField(max_length=60, null=True)),
                ('description', models.CharField(max_length=100000, null=True)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery Informations',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('add', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gallery.add')),
            ],
            options={
                'verbose_name': 'Gallery Picture',
                'verbose_name_plural': 'Gallery Pictures',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
