# Generated by Django 3.1.3 on 2020-12-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add',
            options={'managed': True, 'verbose_name': 'User Information', 'verbose_name_plural': 'User Informations'},
        ),
        migrations.AlterField(
            model_name='add',
            name='thumbnail',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterModelTable(
            name='add',
            table='',
        ),
    ]
