# Generated by Django 3.1.2 on 2021-01-20 06:46

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(upload_to=''),
        ),
    ]
