# Generated by Django 3.1.2 on 2021-01-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210120_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
