# Generated by Django 3.1.2 on 2021-01-20 06:58

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210120_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[1024, 768], upload_to=''),
        ),
    ]
