# Generated by Django 3.1.3 on 2020-12-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20201223_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
