# Generated by Django 3.1.3 on 2020-12-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20201223_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
    ]
