# Generated by Django 3.1.2 on 2021-01-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20210120_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='thumbnail',
        ),
    ]
