# Generated by Django 3.1.2 on 2021-01-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_add_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='thumbnail',
            field=models.ImageField(default='f.jpg', upload_to=''),
        ),
    ]
