# Generated by Django 3.1.2 on 2021-01-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_add_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
