# Generated by Django 3.1.3 on 2020-12-22 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_code_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('middle_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('nick_name', models.CharField(max_length=20, null=True)),
                ('mobile1', models.CharField(max_length=20, null=True)),
                ('mobile2', models.CharField(max_length=20, null=True)),
                ('whatsapp', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('father', models.CharField(max_length=50, null=True)),
                ('mother', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('temp_address', models.CharField(max_length=500, null=True)),
                ('parish', models.CharField(max_length=20, null=True)),
                ('dob', models.CharField(max_length=20, null=True)),
                ('blood', models.CharField(max_length=10, null=True)),
                ('occupation', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('occupation_place', models.CharField(max_length=100, null=True)),
                ('spouse_name', models.CharField(max_length=50, null=True)),
                ('spouse_father', models.CharField(max_length=50, null=True)),
                ('spouse_mother', models.CharField(max_length=50, null=True)),
                ('wedding_date', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Information',
                'verbose_name_plural': 'User Informations',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
