# Generated by Django 3.1.3 on 2020-12-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeinvite',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activeinvite',
            name='blood',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='activeinvite',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activeinvite',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='activeinvite',
            name='father',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activeinvite',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activeinvite',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activeinvite',
            name='middle_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activeinvite',
            name='mobile1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activeinvite',
            name='mobile2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activeinvite',
            name='mother',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activeinvite',
            name='nick_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activeinvite',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activeinvite',
            name='occupation_place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activeinvite',
            name='parish',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activeinvite',
            name='spouse_father',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activeinvite',
            name='spouse_mother',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activeinvite',
            name='spouse_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activeinvite',
            name='temp_address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activeinvite',
            name='whatsapp',
            field=models.IntegerField(null=True),
        ),
    ]
