# Generated by Django 3.1.3 on 2020-12-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_activeinvite_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeinvite',
            name='date_edited',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
