# Generated by Django 3.1.2 on 2020-12-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_activeinvite_date_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeinvite',
            name='photo',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to=''),
        ),
    ]
