# Generated by Django 3.1.2 on 2021-01-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20201231_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeinvite',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
