# Generated by Django 3.1.2 on 2021-01-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adinpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('link', models.CharField(max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='')),
            ],
            options={
                'verbose_name': 'In Page Ad',
                'verbose_name_plural': 'In Page Ads',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('link', models.CharField(max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='')),
            ],
            options={
                'verbose_name': 'Main Page Ad',
                'verbose_name_plural': 'Main Page ads',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thought', models.CharField(max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Thought of the Day',
                'verbose_name_plural': 'Thought of the Day',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
