# Generated by Django 3.1.2 on 2021-01-08 10:37

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', tinymce.models.HTMLField(default=' ', verbose_name='overview')),
                ('content', tinymce.models.HTMLField(default=0, verbose_name='content')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment_count', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=50, null=True)),
                ('thumbnail', models.ImageField(default='thumbnail.jpg', upload_to='')),
                ('tag', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': '1) Post',
                'verbose_name_plural': '1) Posts',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.activeinvite')),
            ],
            options={
                'verbose_name': '2) Comment',
                'verbose_name_plural': '2) Comments',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
