# Generated by Django 3.1.3 on 2020-12-28 11:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201227_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=tinymce.models.HTMLField(default=0, verbose_name='overview'),
        ),
    ]
