# Generated by Django 3.1.3 on 2020-12-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
