# Generated by Django 3.1.3 on 2020-12-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201228_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
