# Generated by Django 3.1.2 on 2021-01-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'managed': True, 'verbose_name': '2) Comment', 'verbose_name_plural': '2) Comments'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'managed': True, 'verbose_name': '1) Post', 'verbose_name_plural': '1) Posts'},
        ),
        migrations.AlterModelTable(
            name='comments',
            table='',
        ),
        migrations.AlterModelTable(
            name='post',
            table='',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
