# Generated by Django 3.1.2 on 2021-01-06 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_activeinvite_description'),
        ('blog', '0012_auto_20210105_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.activeinvite'),
        ),
    ]
