# Generated by Django 3.1.2 on 2021-01-08 10:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=500)),
                ('invite_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_code_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pending Invite',
                'verbose_name_plural': 'Pending Invites',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
