# Generated by Django 3.1.2 on 2021-01-05 06:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', tinymce.models.HTMLField(default=0, verbose_name='overview')),
                ('content', tinymce.models.HTMLField(default=0, verbose_name='content')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('thumbnail', models.ImageField(default=0, upload_to='')),
                ('tag', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Post by Admin',
                'verbose_name_plural': 'Posts by Admin',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
