# Generated by Django 3.1.3 on 2020-12-27 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('child_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='tree.tree')),
                ('connected_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_connected_to', to='tree.tree')),
            ],
            options={
                'verbose_name': 'User Information',
                'verbose_name_plural': 'User Informations',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
