# Generated by Django 3.1.2 on 2021-01-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(blank=True, max_length=1000000, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Family Tree',
                'verbose_name_plural': 'Family Tree Informations',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
