# Generated by Django 3.1.3 on 2020-12-27 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='child_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='tree.tree'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='connected_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_connected_to', to='tree.tree'),
        ),
    ]
