# Generated by Django 3.1.3 on 2020-12-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20201227_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
