# Generated by Django 3.1.2 on 2021-01-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_auto_20201227_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={'managed': True, 'verbose_name': 'Family Tree', 'verbose_name_plural': 'Family Tree Informations'},
        ),
    ]
